In [11]:
files = list(trajectory_folder.glob("*"))

print("All files found:")
for f in files:
    print(f.name)

All files found:
task_001_trajectory.json.json
task_002_trajectory.json.json
task_003_trajectory.json.json

In [2]:
all_data = []

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        all_data.append({
            "task_id": data["task_id"],
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": data["review"]["overall_score"]
        })

all_data

[]

In [3]:
import pandas as pd

df = pd.DataFrame(all_data)
df

Empty DataFrame
Columns: []
Index: []

In [5]:
import os

print("Current working directory:")
print(os.getcwd())

Current working directory:
C:\Users\PC

In [7]:
print("Checking folder:", trajectory_folder.resolve())

files = list(trajectory_folder.glob("*"))

print("Files found:")
for f in files:
    print(f.name)

Checking folder: C:\Users\PC\openclaw-trajectory-eval-lab\data\trajectories
Files found:

In [8]:
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("Trajectory files found:")
for file in files:
    print("-", file.name)

Trajectory files found:

In [10]:
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("Trajectory files found:")
for file in files:
    print("-", file.name)

Trajectory files found:

In [12]:
import os

print(os.listdir("F:/openclaw-trajectory-eval-lab/data/trajectories"))

['task_001_trajectory.json.json', 'task_002_trajectory.json.json', 'task_003_trajectory.json.json']

In [13]:
import pandas as pd

scores_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
scores_df

,task_id,task_title,task_understanding_score,planning_score,evidence_grounding_score,reasoning_depth_score,final_answer_score,overall_score,reviewer_comments
0,1,LLM Evaluation Framework Comparison,9,8,8,9,8,8.4,Well-structured comparison and sound recommend...
1,2,RAG Hallucination Research,8,8,9,8,8,8.2,Good balance of explanation and limitations
2,3,Conflicting Information Resolution,9,8,8,9,9,8.6,Strong conflict-resolution logic and good just...

In [14]:
evidence_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")
evidence_df

,task_id,source_id,source_name,source_type,key_point_1,key_point_2,relevance_score
0,1,S1,Framework source 1,documentation,Supports multiple evaluation metrics,Useful for benchmarking and experimentation,9
1,1,S2,Framework source 2,documentation,Extensible for custom evaluators,Good integration capabilities,8
2,1,S3,Framework source 3,documentation,Strong usability and setup simplicity,Suitable for practical testing workflows,8
3,2,S1,RAG source 1,article/paper,Retrieval injects external context into genera...,Grounded context improves factual consistency,9
4,2,S2,RAG source 2,article/paper,Performance depends on retriever quality,Bad retrieval can still mislead answers,9
5,3,S1,Source A,article/blog/paper,Claims technique A is more effective,Uses a narrow experimental setup,7
6,3,S2,Source B,article/blog/paper,Claims technique B is more practical,Uses broader deployment-oriented reasoning,9

In [15]:
print("Average overall score:", round(scores_df["overall_score"].mean(), 2))
print("Highest score:", scores_df["overall_score"].max())
print("Lowest score:", scores_df["overall_score"].min())

Average overall score: 8.4
Highest score: 8.6
Lowest score: 8.2

In [16]:
score_columns = [
    "task_understanding_score",
    "planning_score",
    "evidence_grounding_score",
    "reasoning_depth_score",
    "final_answer_score"
]

scores_df[["task_title"] + score_columns]

,task_title,task_understanding_score,planning_score,evidence_grounding_score,reasoning_depth_score,final_answer_score
0,LLM Evaluation Framework Comparison,9,8,8,9,8
1,RAG Hallucination Research,8,8,9,8,8
2,Conflicting Information Resolution,9,8,8,9,9

In [17]:
evidence_count = evidence_df.groupby("task_id").size().reset_index(name="evidence_count")
evidence_count

   task_id  evidence_count
0        1               3
1        2               2
2        3               2

In [18]:
summary_df = df.merge(
    scores_df[["task_id", "overall_score"]],
    on="task_id",
    how="left"
).merge(
    evidence_count,
    on="task_id",
    how="left"
)

summary_df

KeyError: 'task_id'

In [19]:
df["task_id"] = df["task_id"].astype(int)
scores_df["task_id"] = scores_df["task_id"].astype(int)

KeyError: 'task_id'

In [20]:
print("df columns:", df.columns.tolist())
print("scores_df columns:", scores_df.columns.tolist())

df columns: []
scores_df columns: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']

In [21]:
import json
import pandas as pd
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("Trajectory files found:")
for file in files:
    print("-", file.name)

all_data = []

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        all_data.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": data["review"]["overall_score"]
        })

df = pd.DataFrame(all_data)

print("\ndf preview:")
print(df)
print("\ndf columns:", df.columns.tolist())

Trajectory files found:

df preview:
Empty DataFrame
Columns: []
Index: []

df columns: []

In [22]:
scores_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
print(scores_df.head())
print(scores_df.columns.tolist())

   task_id                           task_title  task_understanding_score  \
0        1  LLM Evaluation Framework Comparison                         9
1        2           RAG Hallucination Research                         8
2        3   Conflicting Information Resolution                         9

   planning_score  evidence_grounding_score  reasoning_depth_score  \
0               8                         8                      9
1               8                         9                      8
2               8                         8                      9

   final_answer_score  overall_score  \
0                   8            8.4
1                   8            8.2
2                   9            8.6

                                   reviewer_comments
0  Well-structured comparison and sound recommend...
1        Good balance of explanation and limitations
2  Strong conflict-resolution logic and good just...
['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']

In [23]:
df["task_id"] = df["task_id"].astype(int)
scores_df["task_id"] = scores_df["task_id"].astype(int)

KeyError: 'task_id'

In [24]:
evidence_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

evidence_count = evidence_df.groupby("task_id").size().reset_index(name="evidence_count")
print(evidence_count)

   task_id  evidence_count
0        1               3
1        2               2
2        3               2

In [25]:
summary_df = df.merge(
    scores_df[["task_id", "overall_score"]],
    on="task_id",
    how="left",
    suffixes=("_trajectory", "_review")
).merge(
    evidence_count,
    on="task_id",
    how="left"
)

summary_df

KeyError: 'task_id'

In [26]:
print(type(df))
print(df)
print(df.columns.tolist())

<class 'pandas.DataFrame'>
Empty DataFrame
Columns: []
Index: []
[]

In [27]:
import json
import pandas as pd
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("Trajectory files found:")
for file in files:
    print("-", file.name)

all_data = []

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        all_data.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": data["review"]["overall_score"]
        })

df = pd.DataFrame(all_data)

print(df)
print(df.columns.tolist())

Trajectory files found:
Empty DataFrame
Columns: []
Index: []
[]

In [28]:
scores_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
evidence_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")

print("df columns:", df.columns.tolist())
print("scores_df columns:", scores_df.columns.tolist())
print("evidence_df columns:", evidence_df.columns.tolist())

df columns: []
scores_df columns: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']
evidence_df columns: ['task_id', 'source_id', 'source_name', 'source_type', 'key_point_1', 'key_point_2', 'relevance_score']

In [29]:
df["task_id"] = df["task_id"].astype(int)
scores_df["task_id"] = scores_df["task_id"].astype(int)
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

KeyError: 'task_id'

In [30]:
evidence_count = evidence_df.groupby("task_id").size().reset_index(name="evidence_count")

summary_df = df.merge(
    scores_df[["task_id", "overall_score"]],
    on="task_id",
    how="left",
    suffixes=("_trajectory", "_review")
).merge(
    evidence_count,
    on="task_id",
    how="left"
)

summary_df

KeyError: 'task_id'

In [31]:
df = None
scores_df = None
evidence_df = None
all_data = []
print("reset done")

reset done

In [32]:
import json
import pandas as pd
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("Files found:", [f.name for f in files])

all_data = []

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        all_data.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(all_data)

print(df)
print("df columns:", df.columns.tolist())

Files found: []
Empty DataFrame
Columns: []
Index: []
df columns: []

In [33]:
scores_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
evidence_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")

print("scores_df columns:", scores_df.columns.tolist())
print("evidence_df columns:", evidence_df.columns.tolist())
print(scores_df.head())
print(evidence_df.head())

scores_df columns: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']
evidence_df columns: ['task_id', 'source_id', 'source_name', 'source_type', 'key_point_1', 'key_point_2', 'relevance_score']
   task_id                           task_title  task_understanding_score  \
0        1  LLM Evaluation Framework Comparison                         9
1        2           RAG Hallucination Research                         8
2        3   Conflicting Information Resolution                         9

   planning_score  evidence_grounding_score  reasoning_depth_score  \
0               8                         8                      9
1               8                         9                      8
2               8                         8                      9

   final_answer_score  overall_score  \
0                   8            8.4
1                   8            8.2
2                   9            8.6

                                   reviewer_comments
0  Well-structured comparison and sound recommend...
1        Good balance of explanation and limitations
2  Strong conflict-resolution logic and good just...
   task_id source_id         source_name    source_type  \
0        1        S1  Framework source 1  documentation
1        1        S2  Framework source 2  documentation
2        1        S3  Framework source 3  documentation
3        2        S1        RAG source 1  article/paper
4        2        S2        RAG source 2  article/paper

                                         key_point_1  \
0               Supports multiple evaluation metrics
1                   Extensible for custom evaluators
2              Strong usability and setup simplicity
3  Retrieval injects external context into genera...
4           Performance depends on retriever quality

                                     key_point_2  relevance_score
0    Useful for benchmarking and experimentation                9
1                  Good integration capabilities                8
2       Suitable for practical testing workflows                8
3  Grounded context improves factual consistency                9
4        Bad retrieval can still mislead answers                9

In [34]:
df.columns = df.columns.str.strip()
scores_df.columns = scores_df.columns.str.strip()
evidence_df.columns = evidence_df.columns.str.strip()

print("df columns:", df.columns.tolist())
print("scores_df columns:", scores_df.columns.tolist())
print("evidence_df columns:", evidence_df.columns.tolist())

AttributeError: Can only use .str accessor with string values, not integer

In [35]:
df.columns = [str(col).strip() for col in df.columns]
scores_df.columns = [str(col).strip() for col in scores_df.columns]
evidence_df.columns = [str(col).strip() for col in evidence_df.columns]

print("df columns:", df.columns.tolist())
print("scores_df columns:", scores_df.columns.tolist())
print("evidence_df columns:", evidence_df.columns.tolist())

df columns: []
scores_df columns: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']
evidence_df columns: ['task_id', 'source_id', 'source_name', 'source_type', 'key_point_1', 'key_point_2', 'relevance_score']

In [36]:
df["task_id"] = df["task_id"].astype(int)
scores_df["task_id"] = scores_df["task_id"].astype(int)
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

KeyError: 'task_id'

In [37]:
print("DF COLUMNS:", df.columns.tolist())
print("DF SHAPE:", df.shape)
print(df.head())

DF COLUMNS: []
DF SHAPE: (0, 0)
Empty DataFrame
Columns: []
Index: []

In [38]:
print("SCORES COLUMNS:", scores_df.columns.tolist())
print("EVIDENCE COLUMNS:", evidence_df.columns.tolist())

SCORES COLUMNS: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']
EVIDENCE COLUMNS: ['task_id', 'source_id', 'source_name', 'source_type', 'key_point_1', 'key_point_2', 'relevance_score']

In [39]:
import json
import pandas as pd
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("FILES:", [f.name for f in files])

rows = []

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)

print("NEW DF COLUMNS:", df.columns.tolist())
print(df)

FILES: []
NEW DF COLUMNS: []
Empty DataFrame
Columns: []
Index: []

In [40]:
scores_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
evidence_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")

print("scores_df columns:", scores_df.columns.tolist())
print("evidence_df columns:", evidence_df.columns.tolist())

scores_df columns: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']
evidence_df columns: ['task_id', 'source_id', 'source_name', 'source_type', 'key_point_1', 'key_point_2', 'relevance_score']

In [42]:
df.columns = [str(c).strip() for c in df.columns]
scores_df.columns = [str(c).strip() for c in scores_df.columns]
evidence_df.columns = [str(c).strip() for c in evidence_df.columns]

df["task_id"] = df["task_id"].astype(int)
scores_df["task_id"] = scores_df["task_id"].astype(int)
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

print("conversion done")

KeyError: 'task_id'

In [1]:
import json
import pandas as pd
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("FILES FOUND:", [f.name for f in files])

rows = []

for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)

print("\nDF COLUMNS:", df.columns.tolist())
print("\nDF SHAPE:", df.shape)
print("\nDF:")
print(df)

FILES FOUND: []

DF COLUMNS: []

DF SHAPE: (0, 0)

DF:
Empty DataFrame
Columns: []
Index: []

In [2]:
from pathlib import Path
import os

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")

print("Folder exists:", trajectory_folder.exists())
print("Folder path:", trajectory_folder)
print("os.listdir:", os.listdir(trajectory_folder))

Folder exists: True
Folder path: F:\openclaw-trajectory-eval-lab\data\trajectories
os.listdir: ['task_001_trajectory.json.json', 'task_002_trajectory.json.json', 'task_003_trajectory.json.json']

In [3]:
from pathlib import Path
import json
import pandas as pd

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("FILES FOUND:", [f.name for f in files])

rows = []
for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)
print(df)
print(df.columns.tolist())

FILES FOUND: []
Empty DataFrame
Columns: []
Index: []
[]

In [4]:
from pathlib import Path
import json
import pandas as pd

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("FILES FOUND:", [f.name for f in files])

rows = []
for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)
print(df)
print(df.columns.tolist())

FILES FOUND: []
Empty DataFrame
Columns: []
Index: []
[]

In [5]:
from pathlib import Path
import json
import pandas as pd

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("FILES FOUND:", [f.name for f in files])

rows = []
for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)
print(df)
print(df.columns.tolist())

FILES FOUND: []
Empty DataFrame
Columns: []
Index: []
[]

In [6]:
scores_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
evidence_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")

df.columns = [str(c).strip() for c in df.columns]
scores_df.columns = [str(c).strip() for c in scores_df.columns]
evidence_df.columns = [str(c).strip() for c in evidence_df.columns]

print("df columns:", df.columns.tolist())
print("scores_df columns:", scores_df.columns.tolist())
print("evidence_df columns:", evidence_df.columns.tolist())

df columns: []
scores_df columns: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']
evidence_df columns: ['task_id', 'source_id', 'source_name', 'source_type', 'key_point_1', 'key_point_2', 'relevance_score']

In [7]:
df["task_id"] = df["task_id"].astype(int)
scores_df["task_id"] = scores_df["task_id"].astype(int)
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

print("type conversion done")

KeyError: 'task_id'

In [1]:
import json
import pandas as pd
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("FILES FOUND:", [f.name for f in files])

rows = []
for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "overall_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)

scores_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
evidence_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")

df.columns = [str(c).strip() for c in df.columns]
scores_df.columns = [str(c).strip() for c in scores_df.columns]
evidence_df.columns = [str(c).strip() for c in evidence_df.columns]

print("\nDF COLUMNS:", df.columns.tolist())
print("SCORES COLUMNS:", scores_df.columns.tolist())
print("EVIDENCE COLUMNS:", evidence_df.columns.tolist())

print("\nDF:")
print(df)

FILES FOUND: []

DF COLUMNS: []
SCORES COLUMNS: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']
EVIDENCE COLUMNS: ['task_id', 'source_id', 'source_name', 'source_type', 'key_point_1', 'key_point_2', 'relevance_score']

DF:
Empty DataFrame
Columns: []
Index: []

In [2]:
scores_df["task_id"] = scores_df["task_id"].astype(int)
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

evidence_count = evidence_df.groupby("task_id").size().reset_index(name="evidence_count")

summary_df = df.merge(
    scores_df[["task_id", "overall_score"]],
    on="task_id",
    how="left",
    suffixes=("_trajectory", "_review")
).merge(
    evidence_count,
    on="task_id",
    how="left"
)

summary_df

KeyError: 'task_id'

In [3]:
print("DF COLUMNS:", df.columns.tolist())
print("SCORES_DF COLUMNS:", scores_df.columns.tolist())
print("EVIDENCE_DF COLUMNS:", evidence_df.columns.tolist())

evidence_count = evidence_df.groupby("task_id").size().reset_index(name="evidence_count")
print("EVIDENCE_COUNT COLUMNS:", evidence_count.columns.tolist())

print("\nDF:")
print(df.head())

print("\nSCORES_DF:")
print(scores_df.head())

print("\nEVIDENCE_COUNT:")
print(evidence_count.head())

DF COLUMNS: []
SCORES_DF COLUMNS: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']
EVIDENCE_DF COLUMNS: ['task_id', 'source_id', 'source_name', 'source_type', 'key_point_1', 'key_point_2', 'relevance_score']
EVIDENCE_COUNT COLUMNS: ['task_id', 'evidence_count']

DF:
Empty DataFrame
Columns: []
Index: []

SCORES_DF:
   task_id                           task_title  task_understanding_score  \
0        1  LLM Evaluation Framework Comparison                         9
1        2           RAG Hallucination Research                         8
2        3   Conflicting Information Resolution                         9

   planning_score  evidence_grounding_score  reasoning_depth_score  \
0               8                         8                      9
1               8                         9                      8
2               8                         8                      9

   final_answer_score  overall_score  \
0                   8            8.4
1                   8            8.2
2                   9            8.6

                                   reviewer_comments
0  Well-structured comparison and sound recommend...
1        Good balance of explanation and limitations
2  Strong conflict-resolution logic and good just...

EVIDENCE_COUNT:
   task_id  evidence_count
0        1               3
1        2               2
2        3               2

In [4]:
import json
import pandas as pd
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

rows = []
for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "trajectory_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)

scores_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
evidence_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")

df.columns = [str(c).strip() for c in df.columns]
scores_df.columns = [str(c).strip() for c in scores_df.columns]
evidence_df.columns = [str(c).strip() for c in evidence_df.columns]

scores_df["task_id"] = scores_df["task_id"].astype(int)
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

print("DF COLUMNS:", df.columns.tolist())
print("SCORES_DF COLUMNS:", scores_df.columns.tolist())
print("EVIDENCE_DF COLUMNS:", evidence_df.columns.tolist())

print(df)

DF COLUMNS: []
SCORES_DF COLUMNS: ['task_id', 'task_title', 'task_understanding_score', 'planning_score', 'evidence_grounding_score', 'reasoning_depth_score', 'final_answer_score', 'overall_score', 'reviewer_comments']
EVIDENCE_DF COLUMNS: ['task_id', 'source_id', 'source_name', 'source_type', 'key_point_1', 'key_point_2', 'relevance_score']
Empty DataFrame
Columns: []
Index: []

In [5]:
evidence_count = evidence_df.groupby("task_id").size().reset_index(name="evidence_count")

summary_df = df.merge(
    scores_df[["task_id", "overall_score"]],
    on="task_id",
    how="left"
).merge(
    evidence_count,
    on="task_id",
    how="left"
)

summary_df = summary_df.rename(columns={"overall_score": "review_score"})
summary_df

KeyError: 'task_id'

In [1]:
import json
import pandas as pd
from pathlib import Path

# Paths
trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
scores_path = Path("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
evidence_path = Path("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")

# Load trajectory JSONs
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))
print("FILES FOUND:", [f.name for f in files])

rows = []
for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "trajectory_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)

# Load CSVs
scores_df = pd.read_csv(scores_path)
evidence_df = pd.read_csv(evidence_path)

# Clean column names
df.columns = [str(c).strip() for c in df.columns]
scores_df.columns = [str(c).strip() for c in scores_df.columns]
evidence_df.columns = [str(c).strip() for c in evidence_df.columns]

# Force correct task_id types
df["task_id"] = pd.to_numeric(df["task_id"], errors="coerce").astype("Int64")
scores_df["task_id"] = pd.to_numeric(scores_df["task_id"], errors="coerce").astype("Int64")
evidence_df["task_id"] = pd.to_numeric(evidence_df["task_id"], errors="coerce").astype("Int64")

# Drop bad rows if any
df = df.dropna(subset=["task_id"]).copy()
scores_df = scores_df.dropna(subset=["task_id"]).copy()
evidence_df = evidence_df.dropna(subset=["task_id"]).copy()

df["task_id"] = df["task_id"].astype(int)
scores_df["task_id"] = scores_df["task_id"].astype(int)
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

# Build evidence count
evidence_count = (
    evidence_df.groupby("task_id")
    .size()
    .reset_index(name="evidence_count")
)

# Merge safely
summary_df = (
    df.merge(
        scores_df[["task_id", "overall_score"]],
        on="task_id",
        how="left"
    )
    .merge(
        evidence_count,
        on="task_id",
        how="left"
    )
    .rename(columns={"overall_score": "review_score"})
)

print("\nDF COLUMNS:", df.columns.tolist())
print("SCORES COLUMNS:", scores_df.columns.tolist())
print("EVIDENCE COLUMNS:", evidence_df.columns.tolist())
print("EVIDENCE_COUNT COLUMNS:", evidence_count.columns.tolist())

print("\nSUMMARY:")
print(summary_df)

FILES FOUND: []

KeyError: 'task_id'

In [2]:
import json
import pandas as pd
from pathlib import Path

# Paths
trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
scores_path = Path("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
evidence_path = Path("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")

# Load trajectory JSONs
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))
print("FILES FOUND:", [f.name for f in files])

rows = []
for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "trajectory_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)

# Load CSVs
scores_df = pd.read_csv(scores_path)
evidence_df = pd.read_csv(evidence_path)

# Clean column names
df.columns = [str(c).strip() for c in df.columns]
scores_df.columns = [str(c).strip() for c in scores_df.columns]
evidence_df.columns = [str(c).strip() for c in evidence_df.columns]

# Force correct task_id types
df["task_id"] = pd.to_numeric(df["task_id"], errors="coerce").astype("Int64")
scores_df["task_id"] = pd.to_numeric(scores_df["task_id"], errors="coerce").astype("Int64")
evidence_df["task_id"] = pd.to_numeric(evidence_df["task_id"], errors="coerce").astype("Int64")

# Drop bad rows if any
df = df.dropna(subset=["task_id"]).copy()
scores_df = scores_df.dropna(subset=["task_id"]).copy()
evidence_df = evidence_df.dropna(subset=["task_id"]).copy()

df["task_id"] = df["task_id"].astype(int)
scores_df["task_id"] = scores_df["task_id"].astype(int)
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

# Build evidence count
evidence_count = (
    evidence_df.groupby("task_id")
    .size()
    .reset_index(name="evidence_count")
)

# Merge safely
summary_df = (
    df.merge(
        scores_df[["task_id", "overall_score"]],
        on="task_id",
        how="left"
    )
    .merge(
        evidence_count,
        on="task_id",
        how="left"
    )
    .rename(columns={"overall_score": "review_score"})
)

print("\nDF COLUMNS:", df.columns.tolist())
print("SCORES COLUMNS:", scores_df.columns.tolist())
print("EVIDENCE COLUMNS:", evidence_df.columns.tolist())
print("EVIDENCE_COUNT COLUMNS:", evidence_count.columns.tolist())

print("\nSUMMARY:")
print(summary_df)

FILES FOUND: []

KeyError: 'task_id'

In [3]:
import json
import pandas as pd
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("FILES FOUND:", [f.name for f in files])
print("NUMBER OF FILES:", len(files))

rows = []

for file in files:
    print("\nREADING:", file.name)
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        print("TOP-LEVEL KEYS:", list(data.keys()))
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "trajectory_score": float(data["review"]["overall_score"])
        })

print("\nROWS BUILT:", rows)
print("ROWS COUNT:", len(rows))

df = pd.DataFrame(rows)

print("\nDF COLUMNS:", df.columns.tolist())
print("DF SHAPE:", df.shape)
print(df)

FILES FOUND: []
NUMBER OF FILES: 0

ROWS BUILT: []
ROWS COUNT: 0

DF COLUMNS: []
DF SHAPE: (0, 0)
Empty DataFrame
Columns: []
Index: []

In [4]:
import os
print(os.listdir("F:/openclaw-trajectory-eval-lab/data/trajectories"))

['task_001_trajectory.json.json', 'task_002_trajectory.json.json', 'task_003_trajectory.json.json']

In [5]:
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

print("FILES FOUND:", [f.name for f in files])

FILES FOUND: ['task_001_trajectory.json', 'task_002_trajectory.json', 'task_003_trajectory.json']

In [6]:
import json
import pandas as pd
from pathlib import Path

trajectory_folder = Path("F:/openclaw-trajectory-eval-lab/data/trajectories")
files = sorted(trajectory_folder.glob("task_*_trajectory.json"))

rows = []
for file in files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)
        rows.append({
            "task_id": int(data["task_id"]),
            "task_title": data["task_title"],
            "difficulty": data["difficulty"],
            "status": data["status"],
            "trajectory_score": float(data["review"]["overall_score"])
        })

df = pd.DataFrame(rows)
print(df)
print(df.columns.tolist())

   task_id                           task_title difficulty     status  \
0        1  LLM Evaluation Framework Comparison       hard  completed
1        2           RAG Hallucination Research     medium  completed
2        3   Conflicting Information Resolution       hard  completed

   trajectory_score
0               8.4
1               8.2
2               8.6
['task_id', 'task_title', 'difficulty', 'status', 'trajectory_score']

In [7]:
import pandas as pd

# Load CSVs
scores_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/evaluation/trajectory_scores.csv")
evidence_df = pd.read_csv("F:/openclaw-trajectory-eval-lab/data/evidence/evidence_tracker.csv")

# Clean column names
scores_df.columns = [str(c).strip() for c in scores_df.columns]
evidence_df.columns = [str(c).strip() for c in evidence_df.columns]

# Convert types
scores_df["task_id"] = scores_df["task_id"].astype(int)
evidence_df["task_id"] = evidence_df["task_id"].astype(int)

# Evidence count
evidence_count = evidence_df.groupby("task_id").size().reset_index(name="evidence_count")

# Merge everything
summary_df = df.merge(
    scores_df[["task_id", "overall_score"]],
    on="task_id",
    how="left"
).merge(
    evidence_count,
    on="task_id",
    how="left"
)

# Rename for clarity
summary_df = summary_df.rename(columns={"overall_score": "review_score"})

summary_df

,task_id,task_title,difficulty,status,trajectory_score,review_score,evidence_count
0,1,LLM Evaluation Framework Comparison,hard,completed,8.4,8.4,3
1,2,RAG Hallucination Research,medium,completed,8.2,8.2,2
2,3,Conflicting Information Resolution,hard,completed,8.6,8.6,2